version: "3.8"

services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.60.0
    command: [ "--config=/conf/otel-collector-config.yaml" ]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config/otel-collector-config.yaml:/conf/otel-collector-config.yaml
    links:
      - zipkin

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    privileged: true

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=eigr-functions-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "eigr-functions-db"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  mysql:
  postgres:
