---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-springboot-example # Mandatory. Name of the Node containing Actor Host Functions
  system: spawn-system # mandatory. Name of the ActorSystem declared in ActorSystem CRD
  namespace: default # Optional. Default namespace is "default"
spec:
  function:
    image: eigr/spawn-springboot-examples:latest # Mandatory
    ports:
      - containerPort: 8091
