---
apiVersion: spawn-eigr.io/v1
kind: ActorSystem
metadata:
  name: spawn-system # Mandatory. Name of the state store
  namespace: default # Optional. Default namespace is "default"
spec:
  mesh: # Optional
    kind: erlang # Optional. Default erlang. Possible values [erlang | quic]
    cookie: default-c21f969b5f03d33d43e04f8f136e7682 # Optional. Only used if kind is erlang
  statestore:
    type: Postgres
    databaseName: eigr-functions-db
    databaseHost: someHost
    databasePort: "5432"
    statestoreCryptoKey: "3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE="
    credentialsSecretRef: postgres-connection-secret # The secret containing connection params
    pool: # Optional
      size: "10"
