---
apiVersion: spawn.eigr.io/v1
kind: Activator
metadata:
  name: rabbitmq-activator # Mandatory. Name of the activator
  namespace: default # Optional. Default namespace is "default"
spec:
  activator:
    type: AMQP
    paramsSecretRef: rabbitmq-connection-secret
  bindings:
    sources:
      - name: amqp-source
        queue: test
    sinks:
      - name: robert-sink
        actor: robert
        command: setLanguage
        # instance-id-binding:
        #   type: header # Possible: none, header, attribute
        #   name: X-Actor-Instance-Id
