---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: spawn-operator-controller
  name: spawn-operator-controller
  namespace: eigr-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spawn-operator-controller
  template:
    metadata:
      labels:
        k8s-app: spawn-operator-controller
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: eigr/spawn-operator:0.1.0
          name: spawn-operator-controller
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      serviceAccountName: spawn-operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: "0"
    eigr_functions_protocol_minor_version: "1"
    proxy_name: spawn
    k8s-app: spawn-operator
  name: activators.spawn-eigr.io
  namespace: eigr-functions
spec:
  group: spawn-eigr.io
  names:
    kind: Activator
    plural: activators
    shortNames:
      - act
      - acts
      - activator
      - activators
    singular: activator
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: "0"
    eigr_functions_protocol_minor_version: "1"
    proxy_name: spawn
    k8s-app: spawn-operator
  name: actorhosts.spawn-eigr.io
  namespace: eigr-functions
spec:
  group: spawn-eigr.io
  names:
    kind: ActorHost
    plural: actorhosts
    shortNames:
      - ac
      - actor
      - actors
      - actorhost
      - actorhosts
    singular: actorhost
  scope: Cluster
  versions:
    - additionalPrinterColumns: []
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: "0"
    eigr_functions_protocol_minor_version: "1"
    proxy_name: spawn
    k8s-app: spawn-operator
  name: actorsystems.spawn-eigr.io
  namespace: eigr-functions
spec:
  group: spawn-eigr.io
  names:
    kind: ActorSystem
    plural: actorsystems
    shortNames:
      - as
      - actorsys
      - actorsystem
      - actorsystems
      - system
    singular: actorsystem
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - events.k8s.io/v1
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - spawn.eigr.io
    resources:
      - activators
    verbs:
      - "*"
  - apiGroups:
      - spawn.eigr.io
    resources:
      - actorhosts
    verbs:
      - "*"
  - apiGroups:
      - spawn.eigr.io
    resources:
      - actorsystems
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
  namespace: eigr-functions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spawn-operator
subjects:
  - kind: ServiceAccount
    name: spawn-operator
    namespace: default
